spring.application.name=demo
server.port=9090
app.title=this is app from DEV properties file
spring.key=this is spring key

# application.properties
management.endpoints.web.exposure.include=health,info,metrics,beans,env
management.endpoints.web.exposure.exclude=shutdown
logging.file.path=logs/
logging.file.name=logs/myapp.log

# Set the maximum size for a single log file (default is 10MB)
logging.logback.rollingpolicy.max-file-size=10MB

## Optional: Set the total size limit for all log archives
#logging.logback.rollingpolicy.total-size-cap=100MB

# Optional: Set the number of days to keep log files
logging.logback.rollingpolicy.max-history=7

# Sets a custom username
spring.security.user.name=admin
# Sets a custom password
spring.security.user.password=admin
