spring.application.name=demo
server.port=8090
app.title=this is app titles
spring.key=this is spring key
spring.profiles.active=dev
# application.properties
management.endpoints.web.exposure.include=health,info,metrics,beans,env
management.endpoints.web.exposure.exclude=shutdown