package com.example.demo;

import com.model.UserReportRequest;
import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.awt.Color;

@Service
public class PdfGenerationService {

    public byte[] generatePdf(UserReportRequest data) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream();
             Document document = new Document()) {

            PdfWriter.getInstance(document, out);
            document.open();

            // Define Fonts
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, Color.BLACK);
            Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 12, Color.DARK_GRAY);
            Font metaFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 10, Color.GRAY);

            // Add Title
            Paragraph title = new Paragraph(data.getTitle(), titleFont);
            title.setSpacingAfter(20);
            document.add(title);

            // Add Description Body
            Paragraph body = new Paragraph(data.getDescription(), bodyFont);
            body.setSpacingAfter(30);
            document.add(body);

            // Add Author Metadata
            Paragraph author = new Paragraph("Generated by: " + data.getAuthor(), metaFont);
            document.add(author);

            document.close();
            return out.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException("Error during PDF creation", e);
        }
    }
}

